version: "2.1"
services:
    irc:
        build:
            context: ./docker
        hostname: irc
        container_name: irc
        ports:
            - "6667:6667"
        volumes:
            - "./sources:/home/ircnet/sources:rw"
            - "./config/ircd.conf:/home/ircnet/ircd/ircd.conf:rw"
        cap_add:
            - SYS_PTRACE
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
        networks:
            - default

networks:
    default:
        ipam:
          driver: default
          config:
          -
            subnet: 192.168.0.0/24
