version: "2.1"
services:
    irc:
        build:
            context: ./docker
        hostname: irc
        container_name: irc
        ports:
            - "6667:6667"
            - "4400:4400"
        volumes:
            - "./config/ircd.conf:/home/ircnet/ircd/lib/ircd.conf:rw"
            - "./config/ircd.motd:/home/ircnet/ircd/lib/ircd.motd:rw"
            - "./config/newserv.conf:/home/ircnet/newserv-master/newserv.conf:rw"
            - "./newserv-db/chanserv.db:/home/ircnet/newserv-master/chanserv.db"
            - "./newserv-db/fakeusers.db:/home/ircnet/newserv-master/fakeusers.db"
            - "./newserv-db/newserv.db:/home/ircnet/newserv-master/newserv.db"
            - "./newserv-db/noperserv.db:/home/ircnet/newserv-master/noperserv.db"
        cap_add:
            - SYS_PTRACE
        environment:
            - DEV_UID=${DEV_UID}
            - DEV_GID=${DEV_GID}
            - IRCU_VERSION=${IRCU_VERSION}
            - IRCU_SOURCES=${IRCU_SOURCES}
        networks:
            - default

networks:
    default:
        ipam:
          driver: default
          config:
          -
            subnet: 192.168.0.0/24
